language: go
go:
  - 1.7.1
  - 1.6.3
  - 1.5.4

sudo: false

before_install:
  - git config --global url."https://".insteadOf git://
  - go get -u github.com/golang/lint/golint
  - mkdir -p $GOPATH/src/github.com/vbatts && ln -sf $(pwd) $GOPATH/src/github.com/vbatts/dedupe-linker
  - go get ./...

install: true

script:
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v ./...
  - go build -x github.com/vbatts/dedupe-linker
